name: VoiceStudio
options:
  bundleIdPrefix: com.voicestudio
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: "0.15.0"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: "1.0.0"

targets:
  VoiceStudio:
    type: application
    platform: macOS
    sources:
      - VoiceStudio
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voicestudio.app
        PRODUCT_NAME: Voice Studio
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: VoiceStudio/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: VoiceStudio/Resources/VoiceStudio.entitlements
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: WhisperKit
      - package: KeyboardShortcuts
      - package: LaunchAtLogin
    info:
      path: VoiceStudio/Resources/Info.plist
      properties:
        NSMicrophoneUsageDescription: "Voice Studio needs microphone access to transcribe your speech."
        LSUIElement: true
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
    entitlements:
      path: VoiceStudio/Resources/VoiceStudio.entitlements
      properties:
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true
        com.apple.security.app-sandbox: false
